[feature/RF-158] make a breadcrumbs
MirgradR/yea-market-client pull request #11
Opened 2024-06-03 19:05 UTC by beckyuldashev

Насчет универсальности. Может оставить вариант без передачи списка путей? Потому что мы можем с помощью useLocation и так получить пути

2024-06-03 19:52 UTC, PerelomaDenis commented
> Насчет универсальности. Может оставить вариант без передачи списка путей? Потому что мы можем с помощью useLocation и так получить пути

Я бы оставил так. Ведь не всегда путь в url соответствует тому, что в крошках

2024-06-03 20:25 UTC, PerelomaDenis requested changes

2024-06-03 20:25 UTC, PerelomaDenis commented on src/shared/ui/Breadcrumbs/Breadcrumbs.tsx
> +  if (paths) {
Визуально сложный компонент получился. К тому же хук useLocation, как и другие хуки, нельзя вызывать после блока с return, так как они должны вызываться ровно столько, сколько и сам компонент.
У тебя по сути дублируется код, но во второй раз он разбит, что очень усложняет читаемость кода.
ЛУчшим решением я думаю стоит создать переменную по которой ты будешь мапать, и в этой переменной будет либо paths, либо парсинг урла. И в одном месте уже делать return с мапингом из получившегося массива

2024-06-04 06:23 UTC, Serhio46 commented on src/shared/ui/Breadcrumbs/Breadcrumbs.tsx
> +    .filter(path => path !== '');
можно просто path => path

2024-06-04 06:33 UTC, PerelomaDenis approved these changes

2024-06-04 10:07 UTC, MirgradR approved these changes

2024-06-04 10:32 UTC, Serhio46 approved these changes

2024-06-04 12:36 UTC, merged