Feature/rf 152
MirgradR/yea-market-client pull request #13
Opened 2024-06-04 14:07 UTC by maximatory

2024-06-04 14:27 UTC, PerelomaDenis requested changes

2024-06-04 14:27 UTC, PerelomaDenis commented on src/entities/auth/api/authApi.ts
> +export const authApi = createApi({
Советую сделать baseApi в который будут делаться инъекции других эндпоинтов и добавить его в rootReducer вместо authApi. В baseApi будет reducerPath, baseQuery из этого файла и endpoints: () => ({}) 
А уже конкретно тут нужно будет сделать injectEndpoints у baseApi и добавить уже как раз свои эндпоинты логина и регистрации. Это нужно для того, чтобы был единый редьюсер с апихой

2024-06-04 14:27 UTC, PerelomaDenis commented on src/entities/auth/api/authApi.ts
> +        body: JSON.stringify({
Не понимаю для чего здесь перевод в json. Можно же просто получить параметр body без деструктуризации и указать в body в сокращенной записи. Ты же все данные которые деструктурируешь отправляешь на бек. И headers передавать не надо будет

2024-06-04 14:27 UTC, PerelomaDenis commented on src/features/auth/login/ui/LoginForm.tsx
> +        <Button variant="light-form" label="Submit" style={{ width: '100%' }} onClick={() => onSubmit()} />
Тут можно просто указать onClick={onSubmit}

2024-06-04 14:27 UTC, PerelomaDenis commented on src/features/auth/login/ui/LoginForm.tsx
> +        <input className={styles.input} type="text" placeholder="E-mail" onChange={(e) => setEmail(e.target.value)} />
Мне кажется не лучшей практикой писать в jsx функции

2024-06-04 14:27 UTC, PerelomaDenis commented on src/features/auth/login/ui/LoginForm.tsx
> +  const [login] = useLoginMutation()
Советую здесь получить еще isLoading. И добавить к кнопке disabled={isLoading}, чтобы не было возможности кликать пока идет запрос. Тоже самое и с регистрацией

2024-06-04 14:27 UTC, PerelomaDenis commented on src/features/auth/login/ui/LoginForm.tsx
> +    await login({
Раз ты используешь отдельный стейты и функции изменения этих стейтов, то может стоить прям там добавлять эти методы для регистра и обрезки пробелов. А уэе тут просто написать сокращенно `{
email,
password
}`
Тоже самое и в регистрации

2024-06-05 16:22 UTC, maximatory commented on src/entities/auth/api/authApi.ts
> +export const authApi = createApi({
готово

2024-06-05 16:22 UTC, maximatory commented on src/entities/auth/api/authApi.ts
> +        body: JSON.stringify({
мне кажется в развернутом виде понятнее что передается,
но я типизировал эти поля и теперь видим по интерфейсу
сделано

2024-06-05 16:23 UTC, maximatory commented on src/features/auth/login/ui/LoginForm.tsx
> +        <Button variant="light-form" label="Submit" style={{ width: '100%' }} onClick={() => onSubmit()} />
почему то сначала у меня не хотел код работать в таком виде
сделано

2024-06-05 16:23 UTC, maximatory commented on src/features/auth/login/ui/LoginForm.tsx
> +        <input className={styles.input} type="text" placeholder="E-mail" onChange={(e) => setEmail(e.target.value)} />
вынес в отдельную функцию

2024-06-05 16:24 UTC, maximatory commented on src/features/auth/login/ui/LoginForm.tsx
> +  const [login] = useLoginMutation()
добавил, готово

2024-06-05 16:24 UTC, maximatory commented on src/features/auth/login/ui/LoginForm.tsx
> +    await login({
сделано

2024-06-05 17:22 UTC, PerelomaDenis commented on src/features/auth/register/ui/RegisterForm.tsx
> +  const onRegister = async () => {
Тут же не используется эта либа. Я думаю если ты предлагаешь ее использовать, то лучше отдельной задачей

2024-06-05 19:54 UTC, PerelomaDenis approved these changes

2024-06-06 07:35 UTC, MirgradR approved these changes

2024-06-06 08:15 UTC, merged